version: '3'
services:


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8888:80"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_ficsystem 
    links:
      - db 

  db:
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password 
    command: --init-file /init.sql
    ports:
      - '3306:3306'
    environment:
      # - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=db_ficsystem
      # - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
      - ./init.sql:/init.sql

  
  ficsystem:
    # command: mvn clean install
    build:
      context: ./
      dockerfile: ./user/Dockerfile
    image: ficsystem/api

    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - "./ficsystem:/home/ficsystem"
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_ficsystem
#      - MYSQL_ROOT_HOST= '%'
    links:
      - db


  
      
 
